### ISSUE TITLE
sl pr link crashes with "descriptor 'hex' for 'bytes' objects doesn't apply to a 'NoneType' object" if --rev not specified

### ISSUE THREAD

**Issue by lf-** [facebook/sapling#281]
With a local nix build of d81eb55f69b428d7300c43aaa3dfc17393f79238, I tried to link a PR to my branch and seem to have found a bug. Repo is private, but I can try to get info if you need it.

```
 » sl clone https://github.com/my/privaterepo privaterepo
 » cd privaterepo
 » sl goto jadel/my-branch

 » sl pr link 9076
watchman sockpath is set as /opt/facebook/watchman/var/run/watchman/jade-state/sock
** Sapling SCM (version 1be0635ed4072091c1c13a2e6660bd185ee889d8) has crashed:
Traceback (most recent call last):
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/__init__.py", line 106, in run
    dispatch.run(args, fin, fout, ferr, config)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/dispatch.py", line 161, in run
    status = (dispatch(req) or 0) & 255
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/dispatch.py", line 503, in dispatch
    ret = _runcatch(req)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/dispatch.py", line 712, in _runcatch
    return _callcatch(ui, req, _runcatchfunc)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/dispatch.py", line 721, in _callcatch
    return scmutil.callcatch(ui, req, func)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/scmutil.py", line 147, in callcatch
    return func()
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/dispatch.py", line 683, in _runcatchfunc
    return _dispatch(req)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/dispatch.py", line 1218, in _dispatch
    ret = runcommand(
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/ext/undo.py", line 146, in _runcommandwrapper
    result = orig(lui, repo, cmd, fullargs, *args)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/ext/journal.py", line 80, in runcommand
    return orig(lui, repo, cmd, fullargs, *args)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/ext/sparse.py", line 504, in _tracktelemetry
    res = runcommand(lui, repo, *args)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/ext/copytrace.py", line 173, in _runcommand
    return orig(lui, repo, cmd, fullargs, ui, *args, **kwargs)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/dispatch.py", line 913, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/dispatch.py", line 1259, in _runcommand
    return cmdfunc()
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/dispatch.py", line 1217, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **strcmdopt)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/util.py", line 1285, in check
    return func(*args, **kwargs)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/ext/github/__init__.py", line 78, in link_cmd
    return link.link(ui, repo, *args, **opts)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/ext/github/link.py", line 29, in link
    pr_store.map_commit_to_pull_request(ctx.node(), pull_request)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/ext/github/pullrequeststore.py", line 41, in map_commit_to_pull_request
    self._write_mappings(mappings)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/ext/github/pullrequeststore.py", line 64, in _write_mappings
    commits[hex(node)] = entry
TypeError: descriptor 'hex' for 'bytes' objects doesn't apply to a 'NoneType' object


 » sl --debugger pr link 9076
entering debugger - type c to continue starting hg or h for help
--Call--
> /nix/store/03l2x68d3zk4bgicg6a7slgrqcxa3ckn-python3-3.8.15/lib/python3.8/contextlib.py(117)__exit__()
    116
--> 117     def __exit__(self, type, value, traceback):
    118         if type is None:

ipdb> c
watchman sockpath is set as /opt/facebook/watchman/var/run/watchman/jade-state/sock
Traceback (most recent call last):
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/ext/github/__init__.py", line 78, in link_cmd
    return link.link(ui, repo, *args, **opts)
    # args = ('9076')
    # opts = {'rev': ''}
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/ext/github/link.py", line 29, in link
    pr_store.map_commit_to_pull_request(ctx.node(), pull_request)
    # ctx = <workingctx 5cf8e4081e51+>
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/ext/github/pullrequeststore.py", line 41, in map_commit_to_pull_request
    self._write_mappings(mappings)
  File "/Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/ext/github/pullrequeststore.py", line 64, in _write_mappings
    commits[hex(node)] = entry
    # commits = {}
    # entry = {'hostname': 'github.com', 'owner': 'my', 'name': 'privaterepo', 'number': 9076}
TypeError: descriptor 'hex' for 'bytes' objects doesn't apply to a 'NoneType' object
> /Users/jade/dev/nixpkgs/result/lib/python3.8/site-packages/edenscm/ext/github/pullrequeststore.py(64)_write_mappings()
     63         for node, entry in mappings:
---> 64             commits[hex(node)] = entry
     65         with self._repo.lock(), self._repo.transaction("github"):
```

**Comment by lf-** [comment]
Seems to not happen if `--rev` is explicitly specified.

**Comment by DurhamG** [comment]
Thanks for the report.  I've reproduced the issue and am prepping a fix.

**Comment by DurhamG** [comment]
Fixed in https://github.com/facebook/sapling/commit/4f25713feea668f2ec7bf04cada1ec59e6a7c8db
