### ISSUE TITLE
Cannot build reviewstack

### ISSUE THREAD

**Issue by viveksjain** [facebook/sapling#304]
For various reasons I am trying to self-host an instance of reviewstack. To do so I'm following https://github.com/facebook/sapling/blob/main/addons/reviewstack/README.md. I have run `yarn` in the addons/ folder to install all the dependencies. The next step of `yarn codegen` in addons/reviewstack fails:
```
sh$ yarn codegen
yarn run v1.22.19
$ node ./codegen.js
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/vivek.jain/sapling/addons/textmate/dist/extensions' imported from /Users/vivek.jain/sapling/addons/textmate/dist/index.js
    at new NodeError (node:internal/errors:393:5)
    at finalizeResolution (node:internal/modules/esm/resolve:260:11)
    at moduleResolve (node:internal/modules/esm/resolve:879:10)
    at defaultResolve (node:internal/modules/esm/resolve:1087:11)
    at nextResolve (node:internal/modules/esm/loader:161:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:831:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:413:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v19.2.0
node:child_process:960
    throw err;
    ^

Error: Command failed: node --experimental-specifier-resolution=node ../textmate/dist/index.js src/generated/textmate/TextMateGrammarManifest.ts ../reviewstack.dev/public/generated/textmate
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/vivek.jain/sapling/addons/textmate/dist/extensions' imported from /Users/vivek.jain/sapling/addons/textmate/dist/index.js
    at new NodeError (node:internal/errors:393:5)
    at finalizeResolution (node:internal/modules/esm/resolve:260:11)
    at moduleResolve (node:internal/modules/esm/resolve:879:10)
    at defaultResolve (node:internal/modules/esm/resolve:1087:11)
    at nextResolve (node:internal/modules/esm/loader:161:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:831:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:413:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v19.2.0

    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at Object.<anonymous> (/Users/vivek.jain/sapling/addons/reviewstack/textmate.js:55:15)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(877) [Uint8Array] [
      110, 111, 100, 101,  58, 105, 110, 116, 101, 114, 110,  97,
      108,  47, 101, 114, 114, 111, 114, 115,  58,  52,  56,  52,
       10,  32,  32,  32,  32,  69, 114, 114, 111, 114,  67,  97,
      112, 116, 117, 114, 101,  83, 116,  97,  99, 107,  84, 114,
       97,  99, 101,  40, 101, 114, 114,  41,  59,  10,  32,  32,
       32,  32,  94,  10,  10,  69, 114, 114, 111, 114,  32,  91,
       69,  82,  82,  95,  77,  79,  68,  85,  76,  69,  95,  78,
       79,  84,  95,  70,  79,  85,  78,  68,  93,  58,  32,  67,
       97, 110, 110, 111,
      ... 777 more items
    ]
  ],
  pid: 34755,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(877) [Uint8Array] [
    110, 111, 100, 101,  58, 105, 110, 116, 101, 114, 110,  97,
    108,  47, 101, 114, 114, 111, 114, 115,  58,  52,  56,  52,
     10,  32,  32,  32,  32,  69, 114, 114, 111, 114,  67,  97,
    112, 116, 117, 114, 101,  83, 116,  97,  99, 107,  84, 114,
     97,  99, 101,  40, 101, 114, 114,  41,  59,  10,  32,  32,
     32,  32,  94,  10,  10,  69, 114, 114, 111, 114,  32,  91,
     69,  82,  82,  95,  77,  79,  68,  85,  76,  69,  95,  78,
     79,  84,  95,  70,  79,  85,  78,  68,  93,  58,  32,  67,
     97, 110, 110, 111,
    ... 777 more items
  ]
}

Node.js v19.2.0
error Command failed with exit code 1.
node:child_process:960
    throw err;
    ^

Error: Command failed: yarn run textmate
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/vivek.jain/sapling/addons/textmate/dist/extensions' imported from /Users/vivek.jain/sapling/addons/textmate/dist/index.js
    at new NodeError (node:internal/errors:393:5)
    at finalizeResolution (node:internal/modules/esm/resolve:260:11)
    at moduleResolve (node:internal/modules/esm/resolve:879:10)
    at defaultResolve (node:internal/modules/esm/resolve:1087:11)
    at nextResolve (node:internal/modules/esm/loader:161:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:831:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:413:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v19.2.0
node:child_process:960
    throw err;
    ^

Error: Command failed: node --experimental-specifier-resolution=node ../textmate/dist/index.js src/generated/textmate/TextMateGrammarManifest.ts ../reviewstack.dev/public/generated/textmate
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/vivek.jain/sapling/addons/textmate/dist/extensions' imported from /Users/vivek.jain/sapling/addons/textmate/dist/index.js
    at new NodeError (node:internal/errors:393:5)
    at finalizeResolution (node:internal/modules/esm/resolve:260:11)
    at moduleResolve (node:internal/modules/esm/resolve:879:10)
    at defaultResolve (node:internal/modules/esm/resolve:1087:11)
    at nextResolve (node:internal/modules/esm/loader:161:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:831:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:413:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v19.2.0

    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at Object.<anonymous> (/Users/vivek.jain/sapling/addons/reviewstack/textmate.js:55:15)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(877) [Uint8Array] [
      110, 111, 100, 101,  58, 105, 110, 116, 101, 114, 110,  97,
      108,  47, 101, 114, 114, 111, 114, 115,  58,  52,  56,  52,
       10,  32,  32,  32,  32,  69, 114, 114, 111, 114,  67,  97,
      112, 116, 117, 114, 101,  83, 116,  97,  99, 107,  84, 114,
       97,  99, 101,  40, 101, 114, 114,  41,  59,  10,  32,  32,
       32,  32,  94,  10,  10,  69, 114, 114, 111, 114,  32,  91,
       69,  82,  82,  95,  77,  79,  68,  85,  76,  69,  95,  78,
       79,  84,  95,  70,  79,  85,  78,  68,  93,  58,  32,  67,
       97, 110, 110, 111,
      ... 777 more items
    ]
  ],
  pid: 34755,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(877) [Uint8Array] [
    110, 111, 100, 101,  58, 105, 110, 116, 101, 114, 110,  97,
    108,  47, 101, 114, 114, 111, 114, 115,  58,  52,  56,  52,
     10,  32,  32,  32,  32,  69, 114, 114, 111, 114,  67,  97,
    112, 116, 117, 114, 101,  83, 116,  97,  99, 107,  84, 114,
     97,  99, 101,  40, 101, 114, 114,  41,  59,  10,  32,  32,
     32,  32,  94,  10,  10,  69, 114, 114, 111, 114,  32,  91,
     69,  82,  82,  95,  77,  79,  68,  85,  76,  69,  95,  78,
     79,  84,  95,  70,  79,  85,  78,  68,  93,  58,  32,  67,
     97, 110, 110, 111,
    ... 777 more items
  ]
}

Node.js v19.2.0
error Command failed with exit code 1.

    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at Object.<anonymous> (/Users/vivek.jain/sapling/addons/reviewstack/codegen.js:17:15)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(106) [Uint8Array] [
       36,  32, 110, 111, 100, 101,  32,  46,  47, 116, 101, 120,
      116, 109,  97, 116, 101,  46, 106, 115,  10, 105, 110, 102,
      111,  32,  86, 105, 115, 105, 116,  32, 104, 116, 116, 112,
      115,  58,  47,  47, 121,  97, 114, 110, 112, 107, 103,  46,
       99, 111, 109,  47, 101, 110,  47, 100, 111,  99, 115,  47,
       99, 108, 105,  47, 114, 117, 110,  32, 102, 111, 114,  32,
      100, 111,  99, 117, 109, 101, 110, 116,  97, 116, 105, 111,
      110,  32,  97,  98, 111, 117, 116,  32, 116, 104, 105, 115,
       32,  99, 111, 109,
      ... 6 more items
    ],
    Buffer(4001) [Uint8Array] [
      110, 111, 100, 101,  58, 105, 110, 116, 101, 114, 110,  97,
      108,  47, 101, 114, 114, 111, 114, 115,  58,  52,  56,  52,
       10,  32,  32,  32,  32,  69, 114, 114, 111, 114,  67,  97,
      112, 116, 117, 114, 101,  83, 116,  97,  99, 107,  84, 114,
       97,  99, 101,  40, 101, 114, 114,  41,  59,  10,  32,  32,
       32,  32,  94,  10,  10,  69, 114, 114, 111, 114,  32,  91,
       69,  82,  82,  95,  77,  79,  68,  85,  76,  69,  95,  78,
       79,  84,  95,  70,  79,  85,  78,  68,  93,  58,  32,  67,
       97, 110, 110, 111,
      ... 3901 more items
    ]
  ],
  pid: 34750,
  stdout: Buffer(106) [Uint8Array] [
     36,  32, 110, 111, 100, 101,  32,  46,  47, 116, 101, 120,
    116, 109,  97, 116, 101,  46, 106, 115,  10, 105, 110, 102,
    111,  32,  86, 105, 115, 105, 116,  32, 104, 116, 116, 112,
    115,  58,  47,  47, 121,  97, 114, 110, 112, 107, 103,  46,
     99, 111, 109,  47, 101, 110,  47, 100, 111,  99, 115,  47,
     99, 108, 105,  47, 114, 117, 110,  32, 102, 111, 114,  32,
    100, 111,  99, 117, 109, 101, 110, 116,  97, 116, 105, 111,
    110,  32,  97,  98, 111, 117, 116,  32, 116, 104, 105, 115,
     32,  99, 111, 109,
    ... 6 more items
  ],
  stderr: Buffer(4001) [Uint8Array] [
    110, 111, 100, 101,  58, 105, 110, 116, 101, 114, 110,  97,
    108,  47, 101, 114, 114, 111, 114, 115,  58,  52,  56,  52,
     10,  32,  32,  32,  32,  69, 114, 114, 111, 114,  67,  97,
    112, 116, 117, 114, 101,  83, 116,  97,  99, 107,  84, 114,
     97,  99, 101,  40, 101, 114, 114,  41,  59,  10,  32,  32,
     32,  32,  94,  10,  10,  69, 114, 114, 111, 114,  32,  91,
     69,  82,  82,  95,  77,  79,  68,  85,  76,  69,  95,  78,
     79,  84,  95,  70,  79,  85,  78,  68,  93,  58,  32,  67,
     97, 110, 110, 111,
    ... 3901 more items
  ]
}

Node.js v19.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
This is on an M1 Mac if it matters.

**Comment by bolinfest** [comment]
Are you online / do you need to enable a proxy of any sort for your environment? This looks to be an error when fetching the TextMate grammars.

**Comment by bolinfest** [comment]
For reference, here is the GitHub Action that builds and deploys reviewstack.dev:

https://github.com/facebook/sapling/blob/main/.github/workflows/reviewstack.dev-deploy.yml

which is done out of the image defined by this Dockerfile (based on Ubuntu 22.04):

https://github.com/facebook/sapling/blob/main/.github/workflows/sapling-cli-ubuntu-22.04.Dockerfile

It happens to be using Node 16, so I'm not sure if that matters? If you're on an M1, presumably you have most of the other dependencies listed in the Dockerfile, such as `curl` and `git`?

**Comment by bolinfest** [comment]
Looking closer at the output, I forgot the script is doing:

```
node --experimental-specifier-resolution=node ../textmate/dist/index.js
```

perhaps `--experimental-specifier-resolution=node` is no longer supported in Node 19?

**Comment by viveksjain** [comment]
Downgrading to node 16 fixes the error, thanks! May be worth mentioning/linking in the README to whatever version of node is currently supported.
