### ISSUE TITLE
`make oss` doesn't leave working binary on os x

### ISSUE THREAD

**Issue by nemith** [facebook/sapling#309]
If i uninstall sapling from homebrew and then run `make oss` a sl binary is created but doesn't work

```
$ ./sl
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/edenscm/__init__.py", line 106, in run
  File "/opt/homebrew/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/edenscm/dispatch.py", line 151, in run
ImportError: cannot import name 'mercurialshim' from 'edenscm' (/opt/homebrew/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/edenscm/__init__.py)
```

**Comment by sggutier** [comment]
It seems that your locally built version of Sapling is still looking for some Homebrew files, presumably because the server for your Homebrew sapling is still running. You can force the sl binary to not use the server by running setting the `CHGDISABLE` environment variable, e.g. `CHGDISABLE=1 ./sl`.

Could you try to kill the server process manually, or running `CHGDISABLE=1 ./sl --kill-chg-daemon` to see if it is of any help?
