### ISSUE TITLE
build(isl): oss isl build failing

### ISSUE THREAD

**Issue by vegerot** [facebook/sapling#510]
Trying to `make oss` is failing for me with the following error on d3af300d7 (`main` at the time of writing) on macOS 13.1

```sh
❯ time make -j install-oss
SAPLING_OSS_BUILD=true HGNAME=sl \
	  /usr/local/bin/python3.8 setup.py  \
	  build_interactive_smartlog \
	  build_py -c -d . \
	  build_clib  \
	  build_ext  -i \
	  build_rust_ext -i -l  \
	  build_pyzip -i \
	  build_mo
downloading with: curl -L https://files.pythonhosted.org/packages/4c/76/1e41fbb365ad20b6efab2e61b0f4751518444c953b390f9b2d36cf97eea0/Cython-0.29.32.tar.gz -o /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/build/Cython-0.29.32.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2039k  100 2039k    0     0  8355k      0 --:--:-- --:--:-- --:--:-- 8570k
setup.py:1720: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  xcode4 = xcode_version.startswith("Xcode") and StrictVersion(
setup.py:1722: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  ) >= StrictVersion("4.0")
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.69s.
output will be written to /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/build/temp.macosx-13-x86_64-cpython-38/edenscm-isl
/Users/m0c0j7y/workspace/github.com/facebook/sapling/addons/isl-server$ yarn run build
yarn run v1.22.19
$ cross-env NODE_ENV=production webpack
assets by status 212 KiB [cached] 7 assets
orphan modules 258 KiB [orphan] 28 modules
runtime modules 6.94 KiB 21 modules
built modules 364 KiB [built]
  cacheable modules 364 KiB
    modules by path ../node_modules/ 76.5 KiB 36 modules
    modules by path ./ 285 KiB
      modules by path ./proxy/*.ts 270 KiB 4 modules
      modules by path ./src/ 5.06 KiB 2 modules
      ./platform/androidstudioServerPlatform.ts 1.21 KiB [built] [code generated]
      ./node_modules/fb-watchman/index.js 8.86 KiB [built] [code generated]
    ../shared/utils.ts 2 KiB [built] [code generated]
  + 14 modules

ERROR in /Users/m0c0j7y/workspace/github.com/facebook/sapling/addons/isl-server/src/analytics/serverSideTracker.ts
./src/analytics/serverSideTracker.ts 54:18-52
[tsl] ERROR in /Users/m0c0j7y/workspace/github.com/facebook/sapling/addons/isl-server/src/analytics/serverSideTracker.ts(54,19)
      TS2554: Expected 0 arguments, but got 2.
ts-loader-default_e3b0c44298fc1c14
 @ ./src/index.ts 10:0-70 22:20-41
 @ ./proxy/server.ts 18:0-50 153:28-46

webpack 5.74.0 compiled with 1 error in 7647 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
node:child_process:960
    throw err;
    ^

Error: Command failed: yarn run build
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at execSync (/Users/m0c0j7y/workspace/github.com/facebook/sapling/addons/isl/release.js:88:24)
    at Object.<anonymous> (/Users/m0c0j7y/workspace/github.com/facebook/sapling/addons/isl/release.js:43:1)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 28909,
  stdout: null,
  stderr: null
}

Node.js v19.5.0
Traceback (most recent call last):
  File "setup.py", line 1847, in <module>
    setup(
  File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "setup.py", line 1225, in run
    subprocess.run(
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/node', 'release.js', '/Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/build/temp.macosx-13-x86_64-cpython-38/edenscm-isl']' returned non-zero exit status 1.
make: *** [oss] Error 1
make -j install-oss  28.44s user 3.55s system 159% cpu 20.049 total
```

**Comment by bolinfest** [comment]
I believe this is working again as of https://github.com/facebook/sapling/commit/2d270362269a98f07cc2906670852dc9e659e7af
