### ISSUE TITLE
Crash when committing

### ISSUE THREAD

**Issue by steveluscher** [facebook/sapling#565]
```
~/src/solana-web3.js$ sl commit -m "This will crash"
** Sapling SCM (version 0.2.20230228-144002-h9440b05e) has crashed:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/edenscm/__init__.py", line 106, in run
    dispatch.run(args, fin, fout, ferr, config)
  File "/usr/lib/python3.8/site-packages/edenscm/dispatch.py", line 161, in run
    status = (dispatch(req) or 0) & 255
  File "/usr/lib/python3.8/site-packages/edenscm/dispatch.py", line 499, in dispatch
    ret = _runcatch(req)
  File "/usr/lib/python3.8/site-packages/edenscm/dispatch.py", line 687, in _runcatch
    return _callcatch(ui, req, _runcatchfunc)
  File "/usr/lib/python3.8/site-packages/edenscm/dispatch.py", line 696, in _callcatch
    return scmutil.callcatch(ui, req, func)
  File "/usr/lib/python3.8/site-packages/edenscm/scmutil.py", line 143, in callcatch
    return func()
  File "/usr/lib/python3.8/site-packages/edenscm/dispatch.py", line 670, in _runcatchfunc
    return _dispatch(req)
  File "/usr/lib/python3.8/site-packages/edenscm/dispatch.py", line 1197, in _dispatch
    ret = runcommand(
  File "/usr/lib/python3.8/site-packages/edenscm/ext/undo.py", line 146, in _runcommandwrapper
    result = orig(lui, repo, cmd, fullargs, *args)
  File "/usr/lib/python3.8/site-packages/edenscm/ext/journal.py", line 80, in runcommand
    return orig(lui, repo, cmd, fullargs, *args)
  File "/usr/lib/python3.8/site-packages/edenscm/ext/sparse.py", line 504, in _tracktelemetry
    res = runcommand(lui, repo, *args)
  File "/usr/lib/python3.8/site-packages/edenscm/ext/copytrace.py", line 164, in _runcommand
    return orig(lui, repo, cmd, fullargs, ui, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/edenscm/dispatch.py", line 886, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/usr/lib/python3.8/site-packages/edenscm/dispatch.py", line 1238, in _runcommand
    return cmdfunc()
  File "/usr/lib/python3.8/site-packages/edenscm/dispatch.py", line 1196, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **strcmdopt)
  File "/usr/lib/python3.8/site-packages/edenscm/util.py", line 1298, in check
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/edenscm/util.py", line 1298, in check
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/edenscm/ext/automv.py", line 71, in mvcheck
    return orig(ui, repo, *pats, **opts)
  File "/usr/lib/python3.8/site-packages/edenscm/util.py", line 1298, in check
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/edenscm/util.py", line 1298, in check
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/edenscm/ext/tweakdefaults.py", line 396, in commitcmd
    return orig(ui, repo, *pats, **opts)
  File "/usr/lib/python3.8/site-packages/edenscm/util.py", line 1298, in check
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/edenscm/util.py", line 1298, in check
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/edenscm/ext/amend/__init__.py", line 266, in commit
    rc = orig(ui, repo, *pats, **opts)
  File "/usr/lib/python3.8/site-packages/edenscm/util.py", line 1298, in check
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/edenscm/commands/__init__.py", line 1696, in commit
    return _docommit(ui, repo, *pats, **opts)
  File "/usr/lib/python3.8/site-packages/edenscm/commands/__init__.py", line 1752, in _docommit
    node = cmdutil.commit(ui, repo, commitfunc, pats, opts)
  File "/usr/lib/python3.8/site-packages/edenscm/cmdutil.py", line 3586, in commit
    return commitfunc(ui, repo, message, matcher, opts)
  File "/usr/lib/python3.8/site-packages/edenscm/commands/__init__.py", line 1742, in commitfunc
    return repo.commit(
  File "/usr/lib/python3.8/site-packages/edenscm/extensions.py", line 590, in closure
    return func(*(args + a), **kw)
  File "/usr/lib/python3.8/site-packages/edenscm/ext/remotenames.py", line 322, in excommit
    res = orig(repo, *args, **opts)
  File "/usr/lib/python3.8/site-packages/edenscm/localrepo.py", line 2633, in commit
    ret = self.commitctx(cctx, True)
  File "/usr/lib/python3.8/site-packages/edenscm/extensions.py", line 590, in closure
    return func(*(args + a), **kw)
  File "/usr/lib/python3.8/site-packages/edenscm/ext/dirsync.py", line 511, in _commitctx
    node = orig(self, ctx, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/edenscm/localrepo.py", line 2810, in commitctx
    n = self.changelog.add(
  File "/usr/lib/python3.8/site-packages/edenscm/extensions.py", line 590, in closure
    return func(*(args + a), **kw)
  File "/usr/lib/python3.8/site-packages/edenscm/ext/treemanifest/__init__.py", line 284, in changelogadd
    node = orig(self, *args)
  File "/usr/lib/python3.8/site-packages/edenscm/changelog2.py", line 401, in add
    text = gitcommittext(
  File "/usr/lib/python3.8/site-packages/edenscm/changelog.py", line 377, in gitcommittext
    sig_bytes = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gpg', '--status-fd=2', '--detach-sign', '--sign', '--armor', '--local-user', '3BFF48753810D085']' returned non-zero exit status 2.
```

I archived the repository for you in case it's useful in diagnosing this: https://drive.google.com/file/d/1JpRslWIkPo2Pu2I8n9N-g2sgVctwqdBX/view?usp=share_link

---
Sapling 0.2.20230228-144002-h9440b05e

**Comment by steveluscher** [comment]
Ugh. Same as #544.
