### ISSUE TITLE
VS Code extension fails with error: Command "sl" was not found

### ISSUE THREAD

**Issue by mlanln** [facebook/sapling#584]
I'm getting this error in the Interactive Smartlog provided by the VS Code extension:

```
Invalid Sapling command. Is Sapling installed correctly?
Command "sl" was not found.
Error: Command "sl" was not found.
    at zo (https://file+.vscode-resource.vscode-cdn.net/Users/mlanln/.vscode/extensions/meta.sapling-scm-0.1.11/dist/webview/isl.js:1481:365593)
    at Ss (https://file+.vscode-resource.vscode-cdn.net/Users/mlanln/.vscode/extensions/meta.sapling-scm-0.1.11/dist/webview/isl.js:1481:73686)
    at Cl (https://file+.vscode-resource.vscode-cdn.net/Users/mlanln/.vscode/extensions/meta.sapling-scm-0.1.11/dist/webview/isl.js:1481:130645)
    at yc (https://file+.vscode-resource.vscode-cdn.net/Users/mlanln/.vscode/extensions/meta.sapling-scm-0.1.11/dist/webview/isl.js:1481:119627)
    at vc (https://file+.vscode-resource.vscode-cdn.net/Users/mlanln/.vscode/extensions/meta.sapling-scm-0.1.11/dist/webview/isl.js:1481:119555)
    at gc (https://file+.vscode-resource.vscode-cdn.net/Users/mlanln/.vscode/extensions/meta.sapling-scm-0.1.11/dist/webview/isl.js:1481:119418)
    at lc (https://file+.vscode-resource.vscode-cdn.net/Users/mlanln/.vscode/extensions/meta.sapling-scm-0.1.11/dist/webview/isl.js:1481:116559)
    at Bi (https://file+.vscode-resource.vscode-cdn.net/Users/mlanln/.vscode/extensions/meta.sapling-scm-0.1.11/dist/webview/isl.js:1481:57532)
    at https://file+.vscode-resource.vscode-cdn.net/Users/mlanln/.vscode/extensions/meta.sapling-scm-0.1.11/dist/webview/isl.js:1481:114166
```

I had installed Sapling with the [homebrew command in the docs](https://sapling-scm.com/docs/introduction/installation/#macos), and `sl` works in the terminal, so not sure what the issue is. The `sl web` link works fine though.

**Comment by mlanln** [comment]
I'm dumb. A restart of VS Code fixed it.
