### ISSUE TITLE
`sl bookmark thing` that doesn't exist remotely seems to fail

### ISSUE THREAD

**Issue by discentem** [facebook/sapling#611]
It's worth noting this repository is completely new and has no content/files yet.

```bash
sl bookmark stage
** Sapling SCM (version 4.4.2) has crashed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/edenscm/__init__.py", line 106, in run
    dispatch.run(args, fin, fout, ferr, config)
  File "/usr/local/lib/python3.8/site-packages/edenscm/dispatch.py", line 161, in run
    status = (dispatch(req) or 0) & 255
  File "/usr/local/lib/python3.8/site-packages/edenscm/dispatch.py", line 499, in dispatch
    ret = _runcatch(req)
  File "/usr/local/lib/python3.8/site-packages/edenscm/dispatch.py", line 687, in _runcatch
    return _callcatch(ui, req, _runcatchfunc)
  File "/usr/local/lib/python3.8/site-packages/edenscm/dispatch.py", line 696, in _callcatch
    return scmutil.callcatch(ui, req, func)
  File "/usr/local/lib/python3.8/site-packages/edenscm/scmutil.py", line 143, in callcatch
    return func()
  File "/usr/local/lib/python3.8/site-packages/edenscm/dispatch.py", line 670, in _runcatchfunc
    return _dispatch(req)
  File "/usr/local/lib/python3.8/site-packages/edenscm/dispatch.py", line 1197, in _dispatch
    ret = runcommand(
  File "/usr/local/lib/python3.8/site-packages/edenscm/ext/undo.py", line 148, in _runcommandwrapper
    result = orig(lui, repo, cmd, fullargs, *args)
  File "/usr/local/lib/python3.8/site-packages/edenscm/ext/journal.py", line 80, in runcommand
    return orig(lui, repo, cmd, fullargs, *args)
  File "/usr/local/lib/python3.8/site-packages/edenscm/ext/sparse.py", line 478, in _tracktelemetry
    res = runcommand(lui, repo, *args)
  File "/usr/local/lib/python3.8/site-packages/edenscm/ext/copytrace.py", line 157, in _runcommand
    return orig(lui, repo, cmd, fullargs, ui, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/edenscm/dispatch.py", line 886, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/usr/local/lib/python3.8/site-packages/edenscm/dispatch.py", line 1238, in _runcommand
    return cmdfunc()
  File "/usr/local/lib/python3.8/site-packages/edenscm/dispatch.py", line 1196, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **strcmdopt)
  File "/usr/local/lib/python3.8/site-packages/edenscm/util.py", line 1374, in check
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/edenscm/util.py", line 1374, in check
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/edenscm/ext/tweakdefaults.py", line 687, in unfilteredcmd
    return orig(*args, **opts)
  File "/usr/local/lib/python3.8/site-packages/edenscm/ext/remotenames.py", line 1124, in exbookmarks
    ret = orig(ui, repo, *args, **opts)
  File "/usr/local/lib/python3.8/site-packages/edenscm/util.py", line 1374, in check
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/edenscm/commands/__init__.py", line 1323, in bookmark
    bookmarks.deactivate(repo)
  File "/usr/local/lib/python3.8/site-packages/edenscm/util.py", line 752, in __exit__
    self.close()
  File "/usr/local/lib/python3.8/site-packages/edenscm/transaction.py", line 72, in _active
    return func(self, *args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/edenscm/transaction.py", line 586, in close
    self.after()
  File "/usr/local/lib/python3.8/site-packages/edenscm/localrepo.py", line 3216, in a
    repo.changelog.inner.updatereferences(repo.metalog())
error.UncategorizedNativeError: target OID for the reference doesn't exist on the repository; class=Reference (4)
```

`sl push --to stage` works fine, even where `stage` does not exist yet.

**Comment by zzl0** [comment]
Closing — cannot reproduce and the issue is too old to investigate further.
