### ISSUE TITLE
[build] isl: isl build fails due to misplaced babel dependency

### ISSUE THREAD

**Issue by vegerot** [facebook/sapling#621]
starting in a9d447350, `make oss` fails with

```sh
copy ../isl-server/dist -> /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/build/temp.macosx-13-x86_64-cpython-38/edenscm-isl/isl-server/dist
copy ../isl-server/node_modules/ws -> /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/build/temp.macosx-13-x86_64-cpython-38/edenscm-isl/isl-server/node_modules/ws
$ yarn run build
yarn run v1.22.19
$ node ./build.js
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '/Users/m0c0j7y/workspace/github.com/facebook/sapling/addons/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/slicedToArray.js' in '/Users/m0c0j7y/workspace/github.com/facebook/sapling/addons/isl/src'


error Command failed with exit code 1.
```

starting in 494696fb525a0cd57af8b4da8fa07a2c0b3ed6af, `make oss` fails with

```sh
copy ../isl-server/dist -> /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/build/temp.macosx-13-x86_64-cpython-38/edenscm-isl/isl-server/dist
copy ../isl-server/node_modules/ws -> /Users/m0c0j7y/workspace/github.com/facebook/sapling/eden/scm/build/temp.macosx-13-x86_64-cpython-38/edenscm-isl/isl-server/node_modules/ws
$ yarn run build
yarn run v1.22.19
$ node ./build.js
Creating an optimized production build...
Failed to compile.

Module not found: Error: You attempted to import /Users/m0c0j7y/workspace/github.com/facebook/sapling/addons/node_modules/@babel/runtime/helpers/esm/toConsumableArray.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.


error Command failed with exit code 1.
...
Error: Command failed: yarn run build
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at execSync (/Users/m0c0j7y/workspace/github.com/facebook/sapling/addons/isl/release.js:88:24)
    at Object.<anonymous> (/Users/m0c0j7y/workspace/github.com/facebook/sapling/addons/isl/release.js:54:1)
...
```

versions:
node: v20.1.0
yarn: 1.22.19

**Comment by quark-zju** [comment]
Does 494696fb525a0cd57af8b4da8fa07a2c0b3ed6af fix this issue?

**Comment by vegerot** [comment]
As I said in the second half of my message, 494696fb525a0cd57af8b4da8fa07a2c0b3ed6af introduces another build error

**Comment by quark-zju** [comment]
Sorry, I didn't read carefully. Let me try to reproduce it in a clean environment.

**Comment by vegerot** [comment]
Thank you!

**Comment by vegerot** [comment]
Still, `make oss` is failing with

```sh
  + 14 modules
webpack 5.76.0 compiled successfully in 4382 ms
Done in 5.65s.
  $ yarn --cwd ./isl run build
yarn run v1.22.19
$ node ./build.js
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Failed to compile.

Module not found: Error: You attempted to import /home/max/workspace/github.com/facebook/sapling/addons/node_modules/@babel/runtime/helpers/esm/classCallCheck.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/home/max/workspace/github.com/facebook/sapling/addons/build-tar.py", line 196, in <module>
    main()
  File "/home/max/workspace/github.com/facebook/sapling/addons/build-tar.py", line 174, in main
    run(yarn + ["--cwd", src_join("isl"), "run", "build"], env={"CI": "false"})
  File "/home/max/workspace/github.com/facebook/sapling/addons/build-tar.py", line 62, in run
    subprocess.run(command, shell=(os.name == "nt"), check=True, cwd=cwd, env=env)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['yarn', '--cwd', './isl', 'run', 'build']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/max/workspace/github.com/facebook/sapling/eden/scm/setup.py", line 1242, in <module>
    setup(
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/max/workspace/github.com/facebook/sapling/eden/scm/setup.py", line 744, in run
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3.10', 'build-tar.py', '-o', '/home/max/workspace/github.com/facebook/sapling/eden/scm/isl-dist.tar.xz']' returned non-zero exit status 1.
make: *** [Makefile:94: local] Error 1
make -j oss  21.59s user 1.97s system 253% cpu 9.279 total
```

What other information can I give to help reproduce?

**Comment by quark-zju** [comment]
Sorry for the late reply. I tried building fresh (by cloning fresh, then running `build-tar.py` from `addons/`) with node v20.9.0 under Ubuntu 22.04. I didn't repro the issue. What is your node version?

<details>
  <summary>Command output</summary>

  ```
  ~/src/sapling/addons$ ./build-tar.py
    $ yarn --cwd . install --prefer-offline
  yarn install v1.22.19
  [1/4] Resolving packages...
  [2/4] Fetching packages...
  warning sapling-scm@0.1.32: The engine "vscode" appears to be invalid.
  [3/4] Linking dependencies...
  warning "@typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
  warning " > reviewstack@0.1.0" has unmet peer dependency "styled-components@4.x || 5.x".
  warning "workspace-aggregator-e2f73c42-0e6b-424c-a089-37453a9cca88 > shared > @primer/react@35.7.0" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
  warning "workspace-aggregator-e2f73c42-0e6b-424c-a089-37453a9cca88 > shared > styled-components@5.3.5" has unmet peer dependency "react-dom@>= 16.8.0".
  warning "workspace-aggregator-e2f73c42-0e6b-424c-a089-37453a9cca88 > shared > styled-components@5.3.5" has unmet peer dependency "react-is@>= 16.8.0".
  warning "workspace-aggregator-e2f73c42-0e6b-424c-a089-37453a9cca88 > shared > ts-jest@27.1.5" has unmet peer dependency "typescript@>=3.8 <5.0".
  warning "workspace-aggregator-e2f73c42-0e6b-424c-a089-37453a9cca88 > isl > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
  warning "workspace-aggregator-e2f73c42-0e6b-424c-a089-37453a9cca88 > isl > ts-loader@9.3.1" has unmet peer dependency "webpack@^5.0.0".
  warning "workspace-aggregator-e2f73c42-0e6b-424c-a089-37453a9cca88 > sapling-scm > circular-dependency-plugin@5.2.2" has unmet peer dependency "webpack@>=4.0.1".
  warning "workspace-aggregator-e2f73c42-0e6b-424c-a089-37453a9cca88 > sapling-scm > copy-webpack-plugin@11.0.0" has unmet peer dependency "webpack@^5.1.0".
  warning "workspace-aggregator-e2f73c42-0e6b-424c-a089-37453a9cca88 > sapling-scm > mini-css-extract-plugin@2.6.1" has unmet peer dependency "webpack@^5.0.0".
  warning "workspace-aggregator-e2f73c42-0e6b-424c-a089-37453a9cca88 > shared > @primer/react > @radix-ui/react-polymorphic@0.0.14" has incorrect peer dependency "react@^16.8 || ^17.0".
  warning "workspace-aggregator-e2f73c42-0e6b-424c-a089-37453a9cca88 > isl > react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
  warning "workspace-aggregator-e2f73c42-0e6b-424c-a089-37453a9cca88 > isl > react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
  [4/4] Building fresh packages...
  Done in 280.24s.
    $ yarn --cwd ./isl-server run build
  yarn run v1.22.19
  $ cross-env NODE_ENV=production webpack
  asset server.js 180 KiB [emitted] [minimized] (name: server) 1 related asset
  asset 212.js 100 KiB [emitted] [minimized] 1 related asset
  asset 367.js 99.4 KiB [emitted] [minimized] (id hint: vendors) 1 related asset
  asset run-proxy.js 13.4 KiB [emitted] [minimized] (name: run-proxy) 1 related asset
  asset child.js 2.04 KiB [emitted] [minimized] (name: child) 1 related asset
  asset 836.js 781 bytes [emitted] [minimized] 1 related asset
  asset 162.js 551 bytes [emitted] [minimized] 1 related asset
  asset 93.js 236 bytes [emitted] [minimized] 1 related asset
  asset 609.js 234 bytes [emitted] [minimized] 1 related asset
  asset 752.js 230 bytes [emitted] [minimized] 1 related asset
  asset 925.js 227 bytes [emitted] [minimized] 1 related asset
  orphan modules 344 KiB [orphan] 33 modules
  runtime modules 6.94 KiB 21 modules
  built modules 617 KiB [built]
    cacheable modules 616 KiB
      modules by path ../node_modules/ 234 KiB 38 modules
      modules by path ./ 378 KiB
        modules by path ./platform/*.ts 2.66 KiB 5 modules
        modules by path ./proxy/*.ts 358 KiB 4 modules
        modules by path ./src/ 8.59 KiB
          ./src/serverPlatform.ts 4.11 KiB [built] [code generated]
          ./src/analytics/tracker.ts 4.48 KiB [built] [code generated]
        ./node_modules/fb-watchman/index.js 8.86 KiB [built] [code generated]
      ../shared/utils.ts 4.6 KiB [built] [code generated]
    + 14 modules
  webpack 5.76.0 compiled successfully in 21330 ms
  Done in 31.17s.
    $ yarn --cwd ./isl run build
  yarn run v1.22.19
  $ node ./build.js
  Creating an optimized production build...
  Browserslist: caniuse-lite is outdated. Please run:
    npx update-browserslist-db@latest
    Why you should do it regularly: https://github.com/browserslist/update-db#readme
  Browserslist: caniuse-lite is outdated. Please run:
    npx update-browserslist-db@latest
    Why you should do it regularly: https://github.com/browserslist/update-db#readme
  Browserslist: caniuse-lite is outdated. Please run:
    npx update-browserslist-db@latest
    Why you should do it regularly: https://github.com/browserslist/update-db#readme
  Browserslist: caniuse-lite is outdated. Please run:
    npx update-browserslist-db@latest
    Why you should do it regularly: https://github.com/browserslist/update-db#readme
  Compiled with warnings.
  
  [eslint]
  src/CommandHistoryAndProgress.tsx
    Line 9:14:  'CommandArg' is defined but never used  @typescript-eslint/no-unused-vars
  
  src/Commit.tsx
    Line 33:9:  'FoldOperation' is defined but never used  @typescript-eslint/no-unused-vars
  
  src/CommitInfoView/GenerateWithAI.tsx
    Line 23:3:  'editedCommitMessages' is defined but never used  @typescript-eslint/no-unused-vars
  
  Search for the keywords to learn more about each warning.
  To ignore, add // eslint-disable-next-line to the line before.
  
  File sizes after gzip:
  
    293.82 kB  build/static/js/main.js
    17.02 kB   build/static/css/main.d82cd478.css
    11.24 kB   build/static/js/136.848de080.chunk.js
    3.61 kB    build/static/js/webview.js
    1.93 kB    build/static/js/927.e2b9dcb2.chunk.js
    652 B      build/static/js/androidStudioRemote.js
    637 B      build/static/js/chromelike_app.js
    633 B      build/static/js/standalone.js
    592 B      build/static/js/androidStudio.js
    282 B      build/static/css/927.9714ab55.chunk.css
    175 B      build/static/css/136.55f6753b.chunk.css
  
  The project was built assuming it is hosted at /.
  You can control this with the homepage field in your package.json.
  
  The build folder is ready to be deployed.
  You may serve it with a static server:
  
    npm install -g serve
    serve -s build
  
  Find out more about deployment here:
  
    https://cra.link/deployment
  
  Done in 168.96s.
  writing isl-dist.tar.xz
  ```
</details>
