### ISSUE TITLE
[ReviewStack] Broken on mobile browser

### ISSUE THREAD

**Issue by sluongng** [facebook/sapling#704]
```ReferenceError: SharedWorker is not defined at new d (https://reviewstack.dev/static/js/main.5d0ef6cb.js:2:215644) at c.sendMessage (https://reviewstack.dev/static/js/main.5d0ef6cb.js:2:217217) at https://reviewstack.dev/static/js/main.5d0ef6cb.js:2:215221 at myGet (https://reviewstack.dev/static/js/recoil@0.7.5-production.js:1:128133) at evaluateSelectorGetter (https://reviewstack.dev/static/js/recoil@0.7.5-production.js:1:105321) at getSelectorLoadableAndUpdateDeps (https://reviewstack.dev/static/js/recoil@0.7.5-production.js:1:108512) at https://reviewstack.dev/static/js/recoil@0.7.5-production.js:1:111081 at https://reviewstack.dev/static/js/recoil@0.7.5-production.js:1:111040 at Object.selectorGet [as get] (https://reviewstack.dev/static/js/recoil@0.7.5-production.js:1:111076) at getNodeLoadable (https://reviewstack.dev/static/js/recoil@0.7.5-production.js:1:30823)```

**Comment by bolinfest** [comment]
Specifically, what browser is this? Strange that it doesn't support SharedWorker...

**Comment by sluongng** [comment]
It was Chrome on Android

**Comment by bolinfest** [comment]
Wow, this is an incredibly longstanding issue:

https://bugs.chromium.org/p/chromium/issues/detail?id=154571
