### ISSUE TITLE
bench building issues please solve this

### ISSUE THREAD

**Issue by shamsdeveloper** [facebook/sapling#920]
$ vite build --base=/assets/helpdesk/desk/ && yarn copy-html-entry
vite v4.1.4 building for production...
✓ 101 modules transformed.
[vite:load-fallback] Could not load /home/frappe/frappe-botsol/apps/helpdesk/desk/src/pages/onboarding/SimpleOnboarding.vue (imported by src/router/index.js): ENOENT: no such file or directory, open '/home/frappe/frappe-botsol/apps/helpdesk/desk/src/pages/onboarding/SimpleOnboarding.vue'
error during build:
Error: Could not load /home/frappe/frappe-botsol/apps/helpdesk/desk/src/pages/onboarding/SimpleOnboarding.vue (imported by src/router/index.js): ENOENT: no such file or directory, open '/home/frappe/frappe-botsol/apps/helpdesk/desk/src/pages/onboarding/SimpleOnboarding.vue'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:887:11)
    at execSync (node:child_process:959:15)
    at run_build_command_for_apps (/home/frappe/frappe-botsol/apps/frappe/esbuild/esbuild.js:436:5)
    at /home/frappe/frappe-botsol/apps/frappe/esbuild/esbuild.js:88:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1570424,
  stdout: null,
  stderr: null
}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:887:11)
    at execSync (node:child_process:959:15)
    at run_build_command_for_apps (/home/frappe/frappe-botsol/apps/frappe/esbuild/esbuild.js:436:5)
    at /home/frappe/frappe-botsol/apps/frappe/esbuild/esbuild.js:88:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1570424,
  stdout: null,
  stderr: null
}

Node.js v20.5.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-botsol/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/frappe/frappe-botsol/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-botsol/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-botsol/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-botsol/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-botsol/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-botsol/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-botsol/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-botsol/apps/frappe/frappe/commands/utils.py", line 86, in build
    bundle(mode, apps=apps, hard_link=hard_link, verbose=verbose, skip_frappe=skip_frappe)
  File "/home/frappe/frappe-botsol/apps/frappe/frappe/build.py", line 256, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/home/frappe/frappe-botsol/apps/frappe/frappe/commands/__init__.py", line 98, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run build --run-build-command' returned non-zero exit status 1.

**Comment by sggutier** [comment]
@shamsdeveloper are there any missing files when checking out, or how is Sapling affecting your build?
