### ISSUE TITLE
experimental branching prs not working in the UI

### ISSUE THREAD

**Issue by Kimeiga** [facebook/sapling#972]
<img width="1586" alt="image" src="https://github.com/user-attachments/assets/87da2432-db7a-432f-9447-911de92126d3">

when you select "sl push" option on the settings for sl's isl, you can't click "Push..." on any commit. Tried turning on and off the draft checkbox and tried reloading the window.

**Comment by Kimeiga** [comment]
if this works it could solve my question in #970 and make me use sapling for everything vcs job and play included :)

**Comment by Kimeiga** [comment]
```
Something went wrong
Cannot read properties of undefined (reading 'title')
TypeError: Cannot read properties of undefined (reading 'title')
    at _ (https://file+.vscode-resource.vscode-cdn.net/Users/hakan.alpay/.vscode/extensions/meta.sapling-scm-0.1.60/dist/webview/BranchingPrModalContent.js:1:584)
    at z (https://file+.vscode-resource.vscode-cdn.net/Users/hakan.alpay/.vscode/extensions/meta.sapling-scm-0.1.60/dist/webview/BranchingPrModalContent.js:1:964)
    at Wm (https://file+.vscode-resource.vscode-cdn.net/Users/hakan.alpay/.vscode/extensions/meta.sapling-scm-0.1.60/dist/webview/webview.js:45:16998)
    at Hf (https://file+.vscode-resource.vscode-cdn.net/Users/hakan.alpay/.vscode/extensions/meta.sapling-scm-0.1.60/dist/webview/webview.js:47:3139)
    at i1 (https://file+.vscode-resource.vscode-cdn.net/Users/hakan.alpay/.vscode/extensions/meta.sapling-scm-0.1.60/dist/webview/webview.js:47:44737)
    at n1 (https://file+.vscode-resource.vscode-cdn.net/Users/hakan.alpay/.vscode/extensions/meta.sapling-scm-0.1.60/dist/webview/webview.js:47:39727)
    at CM (https://file+.vscode-resource.vscode-cdn.net/Users/hakan.alpay/.vscode/extensions/meta.sapling-scm-0.1.60/dist/webview/webview.js:47:39655)
    at Du (https://file+.vscode-resource.vscode-cdn.net/Users/hakan.alpay/.vscode/extensions/meta.sapling-scm-0.1.60/dist/webview/webview.js:47:39508)
    at Zf (https://file+.vscode-resource.vscode-cdn.net/Users/hakan.alpay/.vscode/extensions/meta.sapling-scm-0.1.60/dist/webview/webview.js:47:35875)
    at Zk (https://file+.vscode-resource.vscode-cdn.net/Users/hakan.alpay/.vscode/extensions/meta.sapling-scm-0.1.60/dist/webview/webview.js:47:34826)
```

got this error with "Amend and push"

**Comment by Kimeiga** [comment]
https://github.com/facebook/sapling/blame/daa248bf675f98d12352bff922a144ddf1564d24/addons/isl/src/codeReview/github/BranchingPrModalContent.tsx#L45

is it this line? @evangrayk

**Comment by Kimeiga** [comment]
i realized the other reason i need this to work is because at my company we use aviator and i need my stacked PRs to each point to their respective parent as the base branch and not all point to master as the base branch

i realize that every time i click submit on any of the commits in the stack of commits with the default settings for sapling it will make all of the PRs for each commit have the base branch of master again even if i changed it and this will prevent the workflow from working lol

**Comment by evangrayk** [comment]
Sorry, this feature is not yet ready for use! That's why we have it tucked away in "experimental". Thanks for trying it out though, I'm glad some people actually dig through the settings and find things like this :)

I look forward to getting this to a useable state, I suspect it will be a more applicable workflow for many GitHub users compared to the stacked techniques we currently have. There's still a good amount to do before this is expected to work well, lots of small things to get right in the workflow. Unfortunately I don't have a timeline to give you for this either.

I might need to move this to a more aggressively hidden experimental location, as the gaps here are still pretty major, I don't want to give the wrong idea :P I hope you don't mind if I close this as "intended".

**Comment by Kimeiga** [comment]
By any meager chance would you know the timeline on when this could be supported? It would quite literally save me hours of time a day hahaha

**Comment by Kimeiga** [comment]
Also would there be any way of getting the existing sl pr submit workflow to work with merge queues like aviator and be reviewable on github without review stack?

**Comment by evangrayk** [comment]
unfortunately I don't have any firm timelines. We have a few other internal priorities at the moment. However it's nice to hear validation that this will be valuable.
